import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import studentsRouter from "./students";
import groupsRouter from "./groups";
import staffRouter from "./staff";
import activityRouter from "./activity";
import galleryRouter from "./gallery";
import settingsRouter from "./settings";
import openDayRouter from "./open-day";
import storageRouter from "./storage";
import coursesRouter from "./courses";
import paymentsRouter from "./payments";
import tasksRouter from "./tasks";
import notificationsRouter from "./notifications";
import pushRouter from "./push";
import studentExtrasRouter from "./student-extras";
import rolesRouter from "./roles";
import sessionsRouter from "./sessions";
import studentCollabRouter from "./student-collab";
import checklistsRouter from "./checklists";
import aiRouter from "./ai";
import brandLogosRouter from "./brand-logos";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(studentsRouter);
router.use(groupsRouter);
router.use(staffRouter);
router.use(activityRouter);
router.use(galleryRouter);
router.use(settingsRouter);
router.use(openDayRouter);
router.use(storageRouter);
router.use(coursesRouter);
router.use(paymentsRouter);
router.use(tasksRouter);
router.use(notificationsRouter);
router.use(pushRouter);
router.use(studentExtrasRouter);
router.use(rolesRouter);
router.use(sessionsRouter);
router.use(studentCollabRouter);
router.use(checklistsRouter);
router.use(aiRouter);
router.use(brandLogosRouter);

export default router;
